apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "kore-helm-repo"
  labels:
    app: kore
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kore-helm-repo
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
  assemblyPhase: "Pending"
  descriptor:
    version: ""
    description: "A repository for Kore helm3 charts"
    type: ""
---
apiVersion: v1
kind: Service
metadata:
  name: kore-helm-repo
  labels:
    app.kubernetes.io/name: kore-help-repo
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: kore-helm-repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kore-help-repo
  name: kore-helm-repo
spec:
  selector:
    matchLabels:
      app: kore-helm-repo
  serviceName: kore-helm-repo
  template:
    metadata:
      labels:
        app: kore-helm-repo
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/appvia/kore-helm-repo:v0.0.4
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
