---
version: '3'
services:
  hub-apiserver:
    image: quay.io/appvia/hub-apiserver:v0.0.2
    environment:
      KUBE_API_SERVER: http://kube-apiserver:8080
      DEX_PUBLIC_URL: http://${LOCALHOST_DNS}:5556
      DEX_GRPC_SERVER: dex-operator
      HUB_ADMIN_PASS: Pa55w0rd
    ports:
      - 10080:10080
    restart: always

  hub-ui:
    image: quay.io/appvia/hub-ui:v0.0.2
    environment:
      HUB_API_URL: http://hub-apiserver:10080/api/v1alpha1
      REDIS_URL: redis://redis:6379
      AUTH_URL: http://${LOCALHOST_DNS}:5556
    ports:
      - 3000:3000
    restart: always

  redis:
    image: redis:5
    ports:
      - 6379:6379

  gke-operator:
    image: quay.io/appvia/gke-operator:v0.0.2

  kube-operator:
    image: quay.io/appvia/kube-operator:v0.0.2
