---
version: '3'
services:
  kore-apiserver:
    image: quay.io/appvia/kore-apiserver:v0.0.15
    env_file: ../../demo.env
    environment:
      KORE_ADMIN_PASS: password
      KORE_ADMIN_TOKEN: password
      KORE_API_PUBLIC_URL: http://localhost:10080
      KORE_UI_PUBLIC_URL: http://localhost:3000
      KORE_AUTHENTICATION_PLUGINS: basicauth,admintoken,openid
      KORE_CERTIFICATE_AUTHORITY: hack/ca/ca.pem
      KORE_CERTIFICATE_AUTHORITY_KEY: hack/ca/ca-key.pem
      KUBE_API_SERVER: http://kube-apiserver:8080
      USERS_DB_URL: root:pass@tcp(database:3306)/kore?parseTime=true
      VERBOSE: 'true'
    ports:
      - 10080:10080
    restart: always
    # Used to source in the test certificate authority
    volumes:
      - ../:/hack

  kore-ui:
    image: quay.io/appvia/kore-ui:v0.0.5
    env_file: ../../demo.env
    environment:
      KORE_BASE_URL: http://localhost:3000
      KORE_API_URL: http://kore-apiserver:10080/api/v1alpha1
      KORE_API_TOKEN: password
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    restart: always

  redis:
    image: redis:5
    ports:
      - 6379:6379
    restart: always
