---
version: '3'
services:
  etcd:
    image: bitnami/etcd:3.4.4
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - 2379:2379

  kube-controller-manager:
    image: gcr.io/google-containers/kube-controller-manager-amd64:v1.15.11
    command:
      - /usr/local/bin/kube-controller-manager
      - --master=http://kube-apiserver:8080

  kube-apiserver:
    image: gcr.io/google-containers/kube-apiserver-amd64:v1.15.11
    command:
      - /usr/local/bin/kube-apiserver
      - --address=0.0.0.0
      - --alsologtostderr
      - --authorization-mode=RBAC
      - --bind-address=0.0.0.0
      - --default-watch-cache-size=200
      - --delete-collection-workers=10
      - --etcd-servers=http://etcd:2379
      - --log-flush-frequency=10s
      - --runtime-config=autoscaling/v1=false
      - --runtime-config=autoscaling/v2beta1=false
      - --runtime-config=autoscaling/v2beta2=false
      - --runtime-config=batch/v1=false
      - --runtime-config=batch/v1beta1=false
      - --runtime-config=networking.k8s.io/v1=false
      - --runtime-config=networking.k8s.io/v1beta1=false
      - --runtime-config=node.k8s.io/v1beta1=false
    ports:
      - 8080:8080
      - 6443:6443
