---
version: '3'
services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - 2379:2379

  kube-controller-manager:
    image: mirrorgooglecontainers/kube-controller-manager-amd64:v1.14.8
    command:
      - /usr/local/bin/kube-controller-manager
      - --master=http://kube-apiserver:8080

  kube-apiserver:
    image: mirrorgooglecontainers/kube-apiserver-amd64:v1.14.8
    command:
      - /usr/local/bin/kube-apiserver
      - --address=0.0.0.0
      - --alsologtostderr
      - --authorization-mode=RBAC
      - --bind-address=0.0.0.0
      - --default-watch-cache-size=200
      - --delete-collection-workers=10
      - --etcd-servers=http://etcd:2379
      - --log-flush-frequency=10s
      - --runtime-config=autoscaling/v1=false
      - --runtime-config=autoscaling/v2beta1=false
      - --runtime-config=autoscaling/v2beta2=false
      - --runtime-config=batch/v1=false
      - --runtime-config=batch/v1beta1=false
      - --runtime-config=networking.k8s.io/v1=false
      - --runtime-config=networking.k8s.io/v1beta1=false
      - --runtime-config=node.k8s.io/v1beta1=false
    ports:
      - 8080:8080
      - 6443:6443

  database:
    image: mariadb:bionic
    environment:
      MYSQL_ROOT_PASSWORD: pass
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS kore;' > /docker-entrypoint-initdb.d/init.sql;
        echo 'CREATE DATABASE IF NOT EXISTS audit;' >> /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3306

