---
version: '3'
services:
  dex-operator:
    image: quay.io/appvia/dex:v2.20.0-master_grpc-connectors
    working_dir: /
    command:
      - serve
      - ./hack/setup/dex/config.yaml
    restart: always
    ports:
      - 5556:5556
      - 5557:5557
    volumes:
      - ../:/hack
