---
version: '3'
services:
  redis:
    image: redis:5
    ports:
      - 6379:6379

  hub-apiserver:
    image: quay.io/appvia/hub-apiserver:latest
    environment:
      KUBE_API_SERVER: http://kube-apiserver:8080
      DEX_PUBLIC_URL: http://localhost:5556
      DEX_GRPC_SERVER: dex-operator
    ports:
      - 10080:10080
    restart: always
