---
version: '3'
services:
  hub-apiserver:
    image: quay.io/appvia/hub-apiserver:latest
    environment:
      KUBE_API_SERVER: http://kube-apiserver:8080
    ports:
      - 10080:10080
    restart: always
