---
version: '3'
services:
  redis:
    image: redis:5
    ports:
      - 6379:6379

  hub-apiserver:
    image: quay.io/appvia/hub-apiserver:latest
    environment:
      KUBE_API_SERVER: http://kube-apiserver:8080
      DEX_PUBLIC_URL: http://localhost:5556
      DEX_GRPC_SERVER: dex-operator
      HUB_ADMIN_PASS: Pa55w0rd
      DATABASE_URL: root:pass@tcp(database:3306)/hub?parseTime=true
      HUB_ADMIN_TOKEN: password
      HUB_CERTIFICATE_AUTHORITY_KEY: /hack/ca/ca-key.pem
      HUB_CERTIFICATE_AUTHORITY: /hack/ca/ca.pem
      HUB_CLIENT_ID: broker
      HUB_CLIENT_SECRET: 2a959c78-134f-4daa-bfef-5cfd96d45948
      HUB_DISCOVERY_URL: https://sso.labs.appvia.io/auth/realms/hub
      HUB_AUTHENTICATION_PLUGINS: openid,admintoken
    ports:
      - 10080:10080
    volumes:
      - ../:/hack
    restart: always
