apiVersion: v1
kind: Namespace
metadata:
  name: captain-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: captain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: captain-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmrequests.app.alauda.io
spec:
  group: app.alauda.io
  version: v1alpha1
  names:
    kind: HelmRequest
    listKind: HelmRequestList
    plural: helmrequests
    singular: helmrequest
    shortNames:
      - hr
  additionalPrinterColumns:
    - name: Chart
      type: string
      description: The chart of this HelmRequest
      JSONPath: .spec.chart
    - name: Version
      type: string
      description: Version of this chart
      JSONPath: .spec.version
    - name: Namespace
      type: string
      description: The namespace which the chart deployed to
      JSONPath: .spec.namespace
    - name: AllCluster
      type: boolean
      description: Is this chart will be installed to all cluster
      JSONPath: .spec.installToAllClusters
    - name: Phase
      type: string
      description: The phase of this HelmRequest
      JSONPath: .status.phase
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - chart
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chartrepos.app.alauda.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: app.alauda.io
  version: v1alpha1
  names:
    kind: ChartRepo
    listKind: ChartRepoList
    plural: chartrepos
    singular: chartrepo
    shortNames:
      - ctr
  additionalPrinterColumns:
    - name: URL
      type: string
      description: The url of this chart repo
      JSONPath: .spec.url
    - name: Phase
      type: string
      description: The phase of this ChartRepo
      JSONPath: .status.phase
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - url
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: charts.app.alauda.io
spec:
    group: app.alauda.io
    version: v1alpha1
    names:
        kind: Chart
        listKind: ChartList
        plural: charts
        singular: chart
    additionalPrinterColumns:
        - name: Version
          type: string
          JSONPath: .spec.versions[0].version
        - name: AppVersion
          type: string
          JSONPath: .spec.versions[0].appVersion
        - name: Age
          type: date
          JSONPath: .metadata.creationTimestamp
    scope: Namespaced
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: captain-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: captain-webhook
      namespace: captain-system
      path: /mutate
  failurePolicy: Fail
  name: mutate-helmrequest.app.alauda.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - app.alauda.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmrequests
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
  name: captain-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: captain-webhook
      namespace: captain-system
      path: /validate
  failurePolicy: Fail
  name: validate-helmrequest.app.alauda.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - app.alauda.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmrequests
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
