---
version: 2

defaults: &defaults
  docker:
    - image: node:10
  environment:
    DOCKER_IMAGE: quay.io/appvia/hub-ui

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          command: |
            npm install
            npm test
            npm run build
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} quay.io
            docker build -t ${DOCKER_IMAGE}:${CIRCLE_TAG:-latest} .
            docker push ${DOCKER_IMAGE}:${CIRCLE_TAG:-latest}

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
