version: 2
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          command: |
            npm install
            npm run lint
            npm test
            npm run build
  release:
    docker:
      - image: docker:19.03-dind
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} quay.io
            docker build -t quay.io/appvia/kore-ui:${CIRCLE_TAG:-latest} .
            docker push quay.io/appvia/kore-ui:${CIRCLE_TAG:-latest}

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*$/
      - release:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*$/
          requires:
            - build
