---
apiVersion: config.hub.appvia.io/v1
kind: Allocation
metadata:
  name: gke
spec:
  name: GKE (London)
  summary: Provide GKE credentials for the London region
  # We reference the above resource when allocating to one
  # or more teams
  resource:
    group: gke.compute.kore.appvia.io
    version: v1alpha1
    kind: GKECredentials
    namespace: kore-admin
    name: gke
  teams:
    - "*"

