apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "helm-operator"
  labels:
    app: kore
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-helm-operator
  componentKinds:
    - group: apps
      kind: Deployment
  assemblyPhase: "Pending"
  descriptor:
    version: ""
    description: "Helm Operator"
    type: ""
