---
# Were create some gke credentials to share
apiVersion: gke.compute.kore.appvia.io/v1alpha1
kind: GKECredentials
metadata:
  name: gke
spec:
  region: GKE_REGION (europe-west2)
  project: GKE_PROJECT_ID
  account: |
    THE JSON SERVICE ACCOUNT KEY
---
# We then allocate the resource to all users in kore
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
  name: gke
spec:
  # The name of the allocation
  name: GKE (London)
  # A short description provided for the UI
  summary: Provide GKE credentials for the London region
  # We reference the above resource when allocating to one
  # or more teams
  resource:
    group: gke.compute.kore.appvia.io
    version: v1alpha1
    kind: GKECredentials
    namespace: kore-admin
    name: gke
  teams:
    - "*"
