---
# Were create some gke credentials to share
apiVersion: gke.compute.kore.appvia.io/v1alpha1
kind: GKECredentials
metadata:
  name: gke
spec:
  region: GKE_REGION (europe-west2)
  project: GKE_PROJECT_ID
  account: |
    THE JSON SERVICE ACCOUNT KEY 