---
apiVersion: aws.compute.kore.appvia.io/v1alpha1
kind: EKSCredentials
metadata:
  name: aws
  namespace: kore-admin
spec:
  accessKeyID: THE SECRET KEY ID
  accountID: THE ACCOUNT ID
  secretAccessKey: THE SECRET ACCESS KEY
---
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
  name: aws
  namespace: kore-admin
spec:
  name: aws
  summary: Default Credentials for building an EKS Cluster
  resource:
    group: aws.compute.kore.appvia.io
    version: v1alpha1
    kind: EKSCredentials
    namespace: kore-admin
    name: aws
  teams:
    - '*'
