apiVersion: aws.compute.kore.appvia.io/v1alpha1
kind: EKSCredentials
metadata:
  creationTimestamp: null
  name: aws
spec:
  secretAccessKey: THE SECRET ACCESS KEY
  accessKeyID: THE SECRET KEY ID
  accountID: THE ACCOUNT ID
status: {}
---
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
  creationTimestamp: null
  name: aws
spec:
  name: aws
  summary: Default Credentials for building an EKS Cluster
  resource:
    group: aws.compute.kore.appvia.io
    version: v1alpha1
    kind: EKSCredentials
    namespace: kore-admin
    name: aws
  teams:
  - '*'
status: {}
