---
apiVersion: clusters.compute.kore.appvia.io/v1
kind: Cluster
metadata:
  name: test-eks-dev
spec:
  description: Test EKS Plan
  kind: EKS
  plan: eks-development
  credentials:
    group: aws.compute.kore.appvia.io
    version: v1alpha1
    kind: EKSCredentials
    name: aws
    namespace: kore-admin
  configuration:
    # Which IP address range can connect to the authentication proxy running in the cluster
    authProxyAllowedIPs:
      - 0.0.0.0/0
    # The role to use for the above if inheritTeamMembers is true
    defaultTeamRole: "cluster-admin"
    description: "This is my test cluster"
    # A domain within the account to provision services within
    domain: example.appvia.io
    enableDefaultTrafficBlock: false
    # Indicates if team members are automatically given access to the cluster
    inheritTeamMembers: true
    # The VPC CIDR block
    privateIPV4Cidr: 10.0.0.0/16
    region: eu-west-2
    version: "1.15"
    nodeGroups:
      - name: eks1
        instanceType: t3.medium
        diskSize: 10
        tags:
          kore: managed
        minSize: 1
        desiredSize: 1
        maxSize: 10
