---
apiVersion: config.kore.appvia.io/v1
kind: Secret
metadata:
  name: gcp
  namespace: kore-admin
spec:
  data:
    key: |
      SERVICE_ACCONT
  description: GCP Origanization
  type: gcp-org
---
apiVersion: gcp.compute.kore.appvia.io/v1alpha1
kind: Organization
metadata:
  name: gcp
spec:
  parentType: organization
  parentID: `gcloud organizations list`
  billingAccount: `gcloud billing list`
  serviceAccount: kore
  credentialsRef:
    name: gcp
    namespace: kore-admin
---
apiVersion: accounts.kore.appvia.io/v1beta1
kind: AccountManagement
metadata:
  name: gke
spec:
  provider: GKE
  managed: true
  organization:
    group: gcp.compute.kore.appvia.io
    version: v1alpha1
    kind: Organization
    namespace: kore-admin
    name: gcp
  rules:
    - name: prod
      plans:
        - gke-production
      prefix: "kore-"
    - name: dev
      plans:
        - gke-development
      prefix: "kore-"
---
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
  name: gke-accounts
spec:
  name: GKE Accounts Provisioning
  summary: Provides the details around GCP account provisioning for the team
  resource:
    group: accounts.kore.appvia.io
    version: v1beta1
    kind: AccountManagement
    namespace: kore-admin
    name: gke
  teams:
    - "*"
---
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
  name: gcp-org
spec:
  name: GCP Organization
  summary: Provides the details around GCP account provisioning for the team
  resource:
    group: gcp.compute.kore.appvia.io
    version: v1alpha1
    kind: Organization
    namespace: kore-admin
    name: gcp
  teams:
    - "*"
