---
apiVersion: clusters.compute.kore.appvia.io/v1
kind: Cluster
metadata:
  name: test-gke-dev
  namespace: a-team
spec:
  description: Test GKE Plan
  kind: GKE
  plan: gke-development
  credentials:
    group: gke.compute.kore.appvia.io
    version: v1alpha1
    kind: GKECredentials
    name: gke
    namespace: kore-admin
  configuration:
    authProxyAllowedIPs:
      - 0.0.0.0/0
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    defaultTeamRole: "cluster-admin"
    description: "This is my test cluster"
    diskSize: 100
    domain: example.appvia.io
    enableAutorepair: true
    enableAutoscaler: true
    enableAutoupgrade: true
    enableHTTPLoadBalancer: true
    enableHorizontalPodAutoscaler: true
    enableIstio: false
    enablePrivateEndpoint: false
    enablePrivateNetwork: false
    enableShieldedNodes: true
    enableStackDriverLogging: true
    enableStackDriverMetrics: true
    enableDefaultTrafficBlock: false
    imageType: COS
    inheritTeamMembers: true
    machineType: n1-standard-2
    maintenanceWindow: "03:00"
    maxSize: 10
    network: default
    region: europe-west2
    size: 1
    subnetwork: default
    version: 1.14.10-gke.27
