---
apiVersion: clusters.compute.hub.appvia.io/v1
kind: ManagedPodSecurityPolicy
metadata:
  name: privileged
spec:
  description: Provides a safe collection of defaults for pods to run under
  policy:
    allowedCapabilities:
    - '*'
    fsGroup:
      rule: RunAsAny
    hostPID: true
    hostIPC: true
    hostNetwork: true
    hostPorts:
    - min: 1
      max: 65536
    privileged: true
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - '*'
