{{ if or .Values.api.endpoint.detect  .Values.ui.endpoint.detect}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kore-endpoint-discover
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kore-endpoint-discover
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kore-endpoint-discover
  namespace: {{ .Release.Namespace }}
{{ if or (eq .Values.api.serviceType "LoadBalancer") (eq .Values.ui.serviceType "LoadBalancer")}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kore.name" . }}-endpoint-discover
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
data:
  loadbalancer_endpoint_detect.sh: |-
{{.Files.Get "scripts/loadbalancer_endpoint_detect.sh" | indent 4}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kore.name" . }}-endpoint-discover
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      serviceAccountName: kore-endpoint-discover
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:{{ .Values.kubectl.version }}
        command: ["/bin/sh"]
        args: 
          - "-c"
          - "/usr/local/bin/loadbalancer_endpoint_detect.sh $0 $@"
          - {{ template "kore.name" . }}
          {{if .Values.api.endpoint.detect}}- {{ include "kore.name" . }}-apiserver{{ end }}
          {{if .Values.ui.endpoint.detect}}- {{ include "kore.name" . }}-portal{{ end }}
        volumeMounts:
        - name: detect-script
          mountPath: /usr/local/bin
      volumes:
        - name: detect-script
          configMap:
            name: {{ template "kore.name" . }}-endpoint-discover
            defaultMode: 0777
  backoffLimit: 1
{{ end }}
{{ end }}
