{{ if .Values.ca.generate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ca.secretName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
data:
  {{ with genCA "kubernetes" 365 }}
  ca.pem: {{ .Cert | b64enc }}
  ca-key.pem: {{ .Key | b64enc }}
  {{ end }}
{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kore.name" . }}-idp
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
stringData:
  KORE_CLIENT_ID: {{ required ".Values.idp.client_id is required!" .Values.idp.client_id }}
  KORE_CLIENT_SCOPES: {{ .Values.idp.client_scopes | join "," }}
  KORE_CLIENT_SECRET: {{ required ".Values.idp.client_secret is required!" .Values.idp.client_secret }}
  KORE_DISCOVERY_URL: {{ required ".Values.idp.discovery_url is required!" .Values.idp.discovery_url }}
  KORE_USER_CLAIMS: {{ .Values.idp.user_claims | join "," }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kore.name" . }}-mysql
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
stringData:
  {{with randAlphaNum 20 }}
  USERS_DB_URL: root:{{ . }}@tcp({{ include "kore.name" $ }}-mysql:3306)/kore?parseTime=true
  MYSQL_ROOT_PASSWORD: {{ . }}
  {{end}}

---
apiVersion: v1
kind: Secret
metadata:
  name: kore-api
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
{{ include "kore.labels" . | indent 4}}
type: Opaque
stringData: 
  KORE_ADMIN_TOKEN: {{randAlphaNum 32 }}
  KORE_ADMIN_PASS: {{randAlphaNum 32 }}
