#
## Pod Security Roles
#
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kore:psp:default
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - default
  verbs: 
  - use  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kore:psp:privileged
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs: 
  - use  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kore:psp:runasroot
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - runasroot
  verbs: 
  - use  
#
## Generic Roles
#
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kore:readonly
rules:   
- nonResourceURLs:
  - "*"  
  verbs: 
  - get  
  - list 
  - watch
- apiGroups:
  - "*"  
  resources:
  - "*"  
  verbs: 
  - get  
  - list 
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kore:secret-management
rules:   
  - apiGroups:
      - "" 
    resources:
      - "secrets"
    verbs: 
      - "*"