# Remove old resources before updating to latest application kind
apiVersion: v1
kind: Service
metadata:
  name: application-controller-manager-service
  namespace: application-system
---
apiVersion: v1
kind: Service
metadata:
  name: application-controller-manager-metrics-service
  namespace: application-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-controller-manager
  namespace: application-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: application-manager-rolebinding
kind: ClusterRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: application-manager-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-proxy-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-leader-election-role
  namespace: application-system
